@startuml
skinparam linetype ortho


  entity User {
      * userId: Long
      --
      * username: String
      * email: String
      * role: String
  }

  entity Employee {
      * employeeId: Long
      * userId: Long
      * supervisorId: Long
      * supSupervisorId: Long
      --
  }

  entity Customer {
      * customerId: Long
      * userId: Long
      * supervisorId: Long
      --
  }

  entity Administrator {
      * adminId: Long
      * userId: Long
      --
  }

  entity Video {
      * videoId: Long
      * tags: List<Tag>
      * comments: List<Comment>
      * questions: List<Question>
      * rating : List<StarRating>
      --
      * title: String
      * description: String
      * save: boolean
      * color: String
      * visibility: VisibilityEnum
      * requestVideo: boolean
  }
  entity StarRating {
        * ratingId: Long
        * userId: Long
        * videoId: Long
        --
        * rating: int
    }
  entity Comment {
      * commentId: Long
      * userId: Long
      * videoId: Long
      --
      * text: String
	  * title: String
  }

  entity Question {
      * questionId: Long
      * videoId: Long
      * answerOptions: List<AnswerOption>
      --
      * questionText: String
  }

  entity AnswerOption {
      * optionId: Long
      * questionId: Long
      --
      * optionText: String
      * isCorrect: boolean
  }

  entity Tag {
      * tagId: Long
      --
      * name: String
  }

  entity LearningPath {
      * pathId: Long
      --
      * title: String
      * description: String
  }

  entity Assignment {
      * assignmentId: Long
      * adminId: Long
      * userId: Long
      * videoId: Long
      * pathId: Long
      --
      * date: datetime
  }

  entity ViewProgress {
      * progressId: Long
      * userId: Long
      * videoId: Long
      --
      * timestamp: datetime
      * progress: int
  }

  entity Notification {
      * notificationId: Long
      * userId: Long
      --
      * text: String
      * timestamp: datetime
  }

  entity Request {
      * requestId: Long
      * userId: Long
      * videoId: Long
      --
      * text: String
      * timestamp: datetime
  }

  User ||--o{ Employee
  User ||--o{ Customer
  User ||--o{ Administrator
  User ||--o{ Assignment
  Assignment ||--o{ Video

  Employee ||--|| User
  Customer ||--|| User
  Administrator ||--|| User
  Employee ||--o{ Employee : supervises
  Administrator ||--o{ Video
  Administrator ||--o{ LearningPath
  User ||--o{ Comment
  Video ||--o{ Comment
  Video ||--o{ Question
  Question ||--o{ AnswerOption
  Video ||--o{ Tag
  User ||--o{ ViewProgress
  Video ||--o{ ViewProgress
  User ||--o{ Notification
  User ||--o{ Request
  Video ||--o{ Request
  Video ||--o{ StarRating


  @enduml
