@startuml
  skinparam linetype ortho

	entity Video {
		* videoId: Long
    * tags: List<Tag>
    * comments: List<Comment>

		--
		* title: String
    * description
    * 5 Star rating
    * Save
    * color: String
    * visibility: VisibilityEnum
    * request Video
	}

	entity Tag {
		* tagId: Long
		--
		* name: String
	}

	entity StarRating {
		* ratingId: Long
		* user: User
		* video: Video
		--
		* rating: int
	}

	entity Comment {
		* commentId: Long
		* user: User
		* video: Video
		--
		* title: String
		* text: String
	}



	entity Question {
		* questionId: Long
		* video: Video
		* qeustions: List<QuestionOption>
		--
		* title: String
		* text: String
	}

	entity QuestionOption {
		* questionOptionId: Long
		--
		* name: String
		* isCorrect: boolean
	}

	Question ||--o{ QuestionOption

	Video ||--o{ StarRating
	Video }o--o{ Tag
	Video ||--o{ Comment
	Video ||--o{ Question

@enduml